apiVersion: apps/v1
kind: Deployment
metadata:
  name: deploy-zuul-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: zuul-server
  template:
    metadata:
      name: spring-cloud-zuul-server
      labels:
        app: zuul-server
    spec:
      containers:
      - name: spring-cloud-zuul-server
        image: ghdalswl77/spring-cloud-zuul-server:1.0
        env:
        - name: EUREKA_SERVER_IP
          value: svc-eureka-server
